const browserGlobals = {
  AbortController: "readonly",
  alert: "readonly",
  antd: "readonly",
  Application: "readonly",
  atob: "readonly",
  Blob: "readonly",
  btoa: "readonly",
  clearInterval: "readonly",
  clearTimeout: "readonly",
  confirm: "readonly",
  console: "readonly",
  crypto: "readonly",
  CustomEvent: "readonly",
  d3: "readonly",
  dayjs: "readonly",
  document: "readonly",
  echarts: "readonly",
  Event: "readonly",
  fetch: "readonly",
  File: "readonly",
  FileReader: "readonly",
  FormData: "readonly",
  Headers: "readonly",
  HTMLCanvasElement: "readonly",
  HTMLElement: "readonly",
  Image: "readonly",
  jssdk: "readonly",
  KeyboardEvent: "readonly",
  localStorage: "readonly",
  location: "readonly",
  markmap: "readonly",
  MutationObserver: "readonly",
  navigator: "readonly",
  Node: "readonly",
  ort: "readonly",
  performance: "readonly",
  Promise: "readonly",
  Request: "readonly",
  ResizeObserver: "readonly",
  Response: "readonly",
  screen: "readonly",
  setInterval: "readonly",
  setTimeout: "readonly",
  TextDecoder: "readonly",
  TextEncoder: "readonly",
  URL: "readonly",
  URLSearchParams: "readonly",
  Vue: "readonly",
  window: "readonly",
  wps: "readonly"
};

const nodeGlobals = {
  __dirname: "readonly",
  __filename: "readonly",
  AbortController: "readonly",
  Buffer: "readonly",
  clearInterval: "readonly",
  clearTimeout: "readonly",
  console: "readonly",
  exports: "readonly",
  fetch: "readonly",
  FormData: "readonly",
  module: "readonly",
  process: "readonly",
  require: "readonly",
  setInterval: "readonly",
  setTimeout: "readonly",
  TextDecoder: "readonly",
  TextEncoder: "readonly",
  URL: "readonly",
  URLSearchParams: "readonly"
};

const commonRules = {
  "constructor-super": "error",
  "for-direction": "error",
  "getter-return": "error",
  "no-async-promise-executor": "error",
  "no-class-assign": "error",
  "no-compare-neg-zero": "error",
  "no-cond-assign": "error",
  "no-const-assign": "error",
  "no-constant-binary-expression": "error",
  "no-constant-condition": ["error", { checkLoops: false }],
  "no-control-regex": "off",
  "no-debugger": "error",
  "no-dupe-args": "error",
  "no-dupe-class-members": "error",
  "no-dupe-else-if": "error",
  "no-dupe-keys": "error",
  "no-duplicate-case": "error",
  "no-empty-character-class": "error",
  "no-empty-pattern": "error",
  "no-ex-assign": "error",
  "no-fallthrough": "error",
  "no-func-assign": "error",
  "no-import-assign": "error",
  "no-invalid-regexp": "error",
  "no-irregular-whitespace": "error",
  "no-loss-of-precision": "error",
  "no-misleading-character-class": "error",
  "no-new-native-nonconstructor": "error",
  "no-obj-calls": "error",
  "no-promise-executor-return": "off",
  "no-prototype-builtins": "off",
  "no-redeclare": "error",
  "no-regex-spaces": "off",
  "no-self-assign": "error",
  "no-setter-return": "error",
  "no-sparse-arrays": "error",
  "no-this-before-super": "error",
  "no-unexpected-multiline": "error",
  "no-unreachable": "error",
  "no-unsafe-finally": "error",
  "no-unsafe-negation": "error",
  "no-unused-vars": "off",
  "no-useless-backreference": "error",
  "require-yield": "error",
  "use-isnan": "error",
  "valid-typeof": "error"
};

export default [
  {
    ignores: [
      "js/vendor/**",
      "js/addon-SDK-*.js",
      "runtime/**",
      "node_modules/**",
      "tools/.gen/**",
      "coverage/**",
      "dist/**"
    ]
  },
  {
    files: ["js/**/*.js", "main.js"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "script",
      globals: browserGlobals
    },
    rules: commonRules
  },
  {
    files: ["tools/**/*.js", "test/**/*.js"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "commonjs",
      globals: nodeGlobals
    },
    rules: commonRules
  }
];
